### ISSUE TITLE
Deletion of shopping lists not working as intended

### ISSUE THREAD

**Issue by FruitVul** [NexdApp/nexd-android#33]
When you try to remove a previously requested shopping list as a seeker by the "bin" symbol the shopping list only removes itself from the list when you go back to the previous screen.

**Comment by FruitVul** [comment]
Duplicate with #24 ?

**Comment by dakna** [comment]
yes, now that https://github.com/NexdApp/nexd-android/pull/24 is merged, I'd say we can close this

**Comment by andre-stefanov** [comment]
> Duplicate with #24 ?

I don't think so
