### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by andre-stefanov** [NexdApp/nexd-android#36]
In order to improve testability we should introduce DI in our project. Which framework should we use for that? Dagger, Koin ..  something else?

**Comment by dakna** [comment]
I'm familiar with Koin, given the relatively small size of this project, I think it would be a good fit.

**Comment by andre-stefanov** [comment]
> I'm familiar with Koin, given the relatively small size of this project, I think it would be a good fit.

Thinking the same. Until now i mainly used Dagger (especially in very big projects) and the overhead of it in comparison to Koin won't be worth it for the moment in my opinion.

**Comment by andre-stefanov** [comment]
Ok then Koin it is. I'm opening issue #55 for that. This discussion can be closed now.
