### ISSUE TITLE
Seeker help requests overview (SeekerOverviewFragment) displays removed/disabled requests.

### ISSUE THREAD

**Issue by andre-stefanov** [NexdApp/nexd-android#42]
![device-2020-04-19-235150](https://user-images.githubusercontent.com/4808362/79700821-e4979280-8298-11ea-9d6a-43526266da78.png)

Disabled/removed requests should not be visible anymore.

**Comment by andre-stefanov** [comment]
This issue is actually wrong. These are not removed/deletedd requests but requests which dont have any articles (articles were removed). We have to concider removing whole request if there are no articles left

**Comment by hunnihundert** [comment]
tried ti reproduce this error but couldn't.

Has it been solved already?
@andre-stefanov

**Comment by hunnihundert** [comment]
reproduction of issue not possible.
looks like it has been solved. will close.
