### ISSUE TITLE
"is Error" branch of when expression never reached

### ISSUE THREAD

**Issue by hunnihundert** [NexdApp/nexd-android#44]
subscribe() method in RegisterViewModel.kt triggered 
`progress.value = Progress.Error(ErrorUtil.parseError(it).firstMessage)`
but in RegisterFragment.kt the "is Error" branch is never triggered

**Comment by claudius-kienle** [comment]
I cant reproduce this bug. E.g when i try to register with a too short password, the snackbar pop up

**Comment by hunnihundert** [comment]
It was an error on my end.
Will close.
