### ISSUE TITLE
Add icons to the registration form

### ISSUE THREAD

**Issue by andre-stefanov** [NexdApp/nexd-android#51]
The designs define icons in the registration form (Register P1).

https://www.figma.com/file/QsK3lJrsgYLcFFIx49g23R/Nexd?node-id=0%3A1

**Comment by mkotyk** [comment]
Did you want to use those assets or the built-in android vector equivalents?

**Comment by andre-stefanov** [comment]
> Did you want to use those assets or the built-in android vector equivalents?

We should use assets from figma. They can be exported there.
