### ISSUE TITLE
Scrolling to the end of the Item List on the "I need something"-Screen resets all displayed amounts to zero

### ISSUE THREAD

**Issue by FruitVul** [NexdApp/nexd-android#67]
When you have entered for example 3 Milk and scroll to the end of the list, the list experiences a reset and all items have an amount of 0. If you check out your list the previously entered 3 Milk is still submitted.

**Comment by hunnihundert** [comment]
a little (hopefully helpful addition): it looks like its a problem with the recycled views. For example, if you type in values for the top 3 items (with open soft keyboard, so only a limited amount of views are visible), scroll down and scroll back up, the entered value will be in other items

**Comment by hunnihundert** [comment]
has been fixed with #94 with the change of HelpRequestCreateArticleBinder.kt
