### ISSUE TITLE
It should be possible to enter different address for a request

### ISSUE THREAD

**Issue by andre-stefanov** [NexdApp/nexd-android#68]

**Comment by hunnihundert** [comment]
looking at the new design that has been posted in the dev channel, after entering the shopping list,  you can enter your address and then confirm your whole order (checking shopping list, address and additional notes).

As the 'enter your address' screen solves this issue, will I be the one implementing it as I am assigned this issue (aka I should wait till the design is out and then start working on it) or will someone else implement it?

**Comment by andre-stefanov** [comment]
![Bild von iOS](https://user-images.githubusercontent.com/4808362/80847516-46001f80-8c10-11ea-8695-d583bdcc65b1.jpg)
